// Lista de cidades para o seletor de "Localização da Loja".
// Capitais + principais cidades. O campo aceita digitar livre (datalist),
// então mesmo cidade fora da lista funciona. Pra produção: trocar pela
// lista completa do IBGE (5.570 municípios) carregada de um JSON.
module.exports = [
  'São Paulo - SP', 'Guarulhos - SP', 'Campinas - SP', 'São Bernardo do Campo - SP',
  'Santo André - SP', 'Osasco - SP', 'Ribeirão Preto - SP', 'Sorocaba - SP',
  'São José dos Campos - SP', 'Santos - SP', 'Bauru - SP', 'Piracicaba - SP',
  'Rio de Janeiro - RJ', 'São Gonçalo - RJ', 'Duque de Caxias - RJ', 'Nova Iguaçu - RJ',
  'Niterói - RJ', 'Campos dos Goytacazes - RJ', 'Petrópolis - RJ', 'Volta Redonda - RJ',
  'Belo Horizonte - MG', 'Uberlândia - MG', 'Contagem - MG', 'Juiz de Fora - MG',
  'Betim - MG', 'Montes Claros - MG', 'Uberaba - MG', 'Governador Valadares - MG',
  'Vitória - ES', 'Vila Velha - ES', 'Serra - ES', 'Cariacica - ES',
  'Curitiba - PR', 'Londrina - PR', 'Maringá - PR', 'Ponta Grossa - PR',
  'Cascavel - PR', 'São José dos Pinhais - PR', 'Foz do Iguaçu - PR', 'Toledo - PR',
  'Porto Alegre - RS', 'Caxias do Sul - RS', 'Pelotas - RS', 'Canoas - RS',
  'Santa Maria - RS', 'Gravataí - RS', 'Novo Hamburgo - RS', 'Passo Fundo - RS',
  'Florianópolis - SC', 'Joinville - SC', 'Blumenau - SC', 'São José - SC',
  'Chapecó - SC', 'Criciúma - SC', 'Itajaí - SC', 'Lages - SC',
  'Salvador - BA', 'Feira de Santana - BA', 'Vitória da Conquista - BA', 'Camaçari - BA',
  'Itabuna - BA', 'Juazeiro - BA', 'Ilhéus - BA', 'Barreiras - BA',
  'Recife - PE', 'Jaboatão dos Guararapes - PE', 'Olinda - PE', 'Caruaru - PE',
  'Petrolina - PE', 'Paulista - PE', 'Cabo de Santo Agostinho - PE', 'Surubim - PE',
  'Fortaleza - CE', 'Caucaia - CE', 'Juazeiro do Norte - CE', 'Maracanaú - CE',
  'Sobral - CE', 'Crato - CE', 'Maranguape - CE',
  'São Luís - MA', 'Imperatriz - MA', 'Timon - MA', 'Caxias - MA',
  'Teresina - PI', 'Parnaíba - PI', 'Picos - PI',
  'Natal - RN', 'Mossoró - RN', 'Parnamirim - RN',
  'João Pessoa - PB', 'Campina Grande - PB', 'Santa Rita - PB',
  'Maceió - AL', 'Arapiraca - AL',
  'Aracaju - SE', 'Nossa Senhora do Socorro - SE',
  'Goiânia - GO', 'Aparecida de Goiânia - GO', 'Anápolis - GO', 'Rio Verde - GO',
  'Brasília - DF',
  'Cuiabá - MT', 'Várzea Grande - MT', 'Rondonópolis - MT', 'Sinop - MT',
  'Campo Grande - MS', 'Dourados - MS', 'Três Lagoas - MS',
  'Manaus - AM', 'Parintins - AM',
  'Belém - PA', 'Ananindeua - PA', 'Santarém - PA', 'Marabá - PA', 'Castanhal - PA',
  'Porto Velho - RO', 'Ji-Paraná - RO',
  'Rio Branco - AC',
  'Boa Vista - RR',
  'Macapá - AP',
  'Palmas - TO', 'Araguaína - TO',
];
